# Pre-commit configuration for Vichintarka FastAPI project
# See https://pre-commit.com for more information

repos:
  # Built-in hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
      - id: end-of-file-fixer
        name: Fix End of Files
      - id: check-yaml
        name: Check YAML
        args: ['--allow-multiple-documents']
      - id: check-json
        name: Check JSON
      - id: check-toml
        name: Check TOML
      - id: check-added-large-files
        name: Check for Added Large Files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
        name: Check for Merge Conflicts
      - id: debug-statements
        name: Debug Statements (Python)
      - id: check-docstring-first
        name: Check Docstring is First
      - id: check-case-conflict
        name: Check for Case Conflicts
      - id: check-executables-have-shebangs
        name: Check that Executables Have Shebangs
      - id: mixed-line-ending
        name: Mixed Line Ending

  # Python code formatting with Black
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: Format Python Code (Black)
        language_version: python3.11
        args: ['--line-length=88', '--target-version=py311']

  # Python import sorting with isort
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: Sort Python Imports (isort)
        args: ['--profile=black', '--line-length=88']

  # Python linting with flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: Lint Python Code (flake8)
        args: ['--max-line-length=88', '--extend-ignore=E203,W503,D100,D101,D103,D104,D106']
        additional_dependencies:
          - flake8-docstrings
          - flake8-bugbear
          - flake8-comprehensions

  # Python type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: Type Check Python Code (mypy)
        additional_dependencies:
          - types-PyYAML
          - types-redis
          - types-requests
        args: ['--ignore-missing-imports', '--no-strict-optional', '--show-error-codes']
        exclude: ^alembic/

  # Python security linting with bandit
  - repo: https://github.com/pycqa/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
        name: Security Lint Python Code (bandit)
        args: ['-r', '.', '--skip', 'B101']
        exclude: ^tests/

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        name: Lint Dockerfile (hadolint)

  # Docker Compose validation
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v3.0.1
    hooks:
      - id: docker-compose-check
        name: Validate Docker Compose

  # YAML linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: Lint YAML Files
        args: ['-d', 'relaxed']

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        name: Lint Shell Scripts

  # Commit message validation
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen
        name: Check Commit Message Format
        stages: [commit-msg]

  # Remove unused imports and variables
  - repo: https://github.com/pycqa/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        name: Remove Unused Imports (autoflake)
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --recursive

  # Upgrade Python syntax
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
        name: Upgrade Python Syntax
        args: [--py39-plus]

# Global configuration
default_stages: [pre-commit]
fail_fast: false

# Exclude patterns
exclude: |
  (?x)^(
      \.git/.*|
      \.vscode/.*|
      __pycache__/.*|
      \.pytest_cache/.*|
      \.mypy_cache/.*|
      \.venv/.*|
      venv/.*|
      migrations/versions/.*|
      .*\.egg-info/.*
  )$
